routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('kontak','Kontak');
Route::resource('lokasi','LokasiController');
Route::resource('pengiriman','PengirimanController');
Route::resource('barang','BarangController');
Route::resource('report','ReportController');


Route::get('/','ReportController@index')->name('homez');
// Route::get('/pengiriman','PengirimanController@index')->name('datakirim');
Route::get('/donut', 'ReportController@index')->name('donut');
Route::get('/lokasichart', 'ReportController@lokasiChart')->name('lokasiChart');
Route::get('/barangchart', 'ReportController@barangChart')->name('barangChart');

Route::get('/dashboard', function()
{

        return view('dashboard.index', [
            'sub' => "Dashboard Pengiriman"
        ]);
});

Route::get('/input_data', function()
{
        return view('dashboard.input_data', [
            'sub' => "Masukan Data"
        ]);

});
Route::post('/input_data', 'ReportController@inputData')->name('inputData');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/barang.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            <a class="btn btn-success" href="{{ route('barang.create') }}">Tambah Barang</a>
            <hr>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Kode Barang</th>
                    <th>Nama</th>
                    <th>Deskripsi</th>
                    <th>Stok</th>
                    <th>Harga</th>
                    <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach($data as $datas)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>ID{{ $datas->kode_barang }}</td>
                        <td>{{ $datas->nama_barang }}</td>
                        <td>{{ $datas->deskripsi }}</td>
                        <td>{{ $datas->stok_barang }}</td>
                        <td>{{ $datas->harga_barang }}</td>
                        <td>
                            <form action="{{ route('barang.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('barang.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/barang_create.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->

            <hr>
            <form action="{{ route('barang.store') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nama">Nama Barang:</label>
                    <input required type="text" class="form-control" id="nama" name="nama">
                </div>
                <div class="form-group">
                    <label for="deskripsi">Deskripsi:</label>
                    <input required type="text" class="form-control" id="deskripsi" name="deskripsi">
                </div>
                <div class="form-group">
                    <label for="stok">Stok:</label>
                    <input required type="text" class="form-control" id="stok" name="stok">
                </div>
                <div class="form-group">
                    <label for="harga">Harga:</label>
                    <input required type="text" class="form-control" id="harga" name="harga">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/barang') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/barang_edit.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <hr>
            @foreach($data as $datas)
            <form action="{{ route('barang.update', $datas->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="kode barang">Kode:</label>
                    <input readonly type="text" class="form-control" id="kode" name="kode" value="ID{{ $datas->kode_barang}}">
                </div>
                <div class="form-group">
                    <label for="nama">nama:</label>
                    <input type="text" class="form-control" id="nama" name="nama" value="{{ $datas->nama_barang }}">
                </div>
                <div class="form-group">
                    <label for="deskripsi">Deskripsi:</label>
                    <input type="text" class="form-control" id="deskripsi" name="deskripsi" value="{{ $datas->deskripsi }}">
                </div>
                <div class="form-group">
                    <label for="stok">Stok:</label>
                    <input type="text" class="form-control" id="stok" name="stok" value="{{ $datas->stok_barang }}">
                </div>
                <div class="form-group">
                    <label for="harga">Harga:</label>
                    <input type="text" class="form-control" id="harga" name="harga" value="{{ $datas->harga_barang }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/barang') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
            @endforeach
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/donutchart.blade.php
@extends('base')
@section('content')
<div class="row">
  <div class="col-lg-4 col-6">
  
  <div class="small-box bg-info">
  <div class="inner">
  <h3>150</h3>
  <p>Total Pengiriman</p>
  </div>
  <div class="icon">
  <i class="ion ion-bag"></i>
  </div>
  <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
  </div>
  </div>
  
  <div class="col-lg-4 col-6">
  
  <div class="small-box bg-success">
  <div class="inner">
  <h3>Jakarta<sup style="font-size: 20px"></sup></h3>
  <p>Lokasi Terbanyak</p>
  </div>
  <div class="icon">
  <i class="ion ion-stats-bars"></i>
  </div>
  <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
  </div>
  </div>
  
  <div class="col-lg-4 col-6">
  
  <div class="small-box bg-warning">
  <div class="inner">
  <h3>44</h3>
  <p>Barang Terbanyak</p>
  </div>
  <div class="icon">
  <i class="ion ion-person-add"></i>
  </div>
  <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
  </div>
  
  
  
  </div>
    <canvas id="myChart" style="height:40vh; width:30vw; margin:0 auto"></canvas>
  </div>

  <div>
    <canvas id="hargaBarangChart" style="height:40vh; width:30vw; margin:0 auto"></canvas>
  </div>
  
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  
  <script>
    const ctx = document.getElementById('myChart');
  
    new Chart(ctx, {
      type: 'doughnut',
      data: {
        labels: ['Pengiriman Diatas 100', 'Pengiriman DIbawah 101'],
        datasets: [{
          label: 'Pengiriman barang diatas 100',
          data: [12, 19],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
  <script>
    const chart = document.getElementById('hargaBarangChart');
  
    new Chart(chart, {
      type: 'doughnut',
      data: {
        labels: ['Harga Diatas 1000', 'Harga DIbawah 1001'],
        datasets: [{
          label: 'Harga barang diatas 1000',
          data: [12, 19],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          y: {
            beginAtZero: true
          }
        }
      }
    });
  </script>
   
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    Anda sudah login, silahkan logout jika ingin mendaftar !
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <h1>Kelompok 1</h1>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/kontak.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            {{-- <a class="btn btn-success" href="{{ route('register') }}">Daftar Sales</a>
            <hr> --}}

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Nama</th>
                    <th>Email</th>
                    <th>Coverage</th>
                    <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach($data as $datas)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $datas->name }}</td>
                        <td>{{ $datas->email }}</td>
                        <td>{{ $datas->alamat }}</td>
                        <td>
                            <form action="{{ route('kontak.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('kontak.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/kontak_create.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <hr>
            <form action="{{ route('kontak.store') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nama">Nama:</label>
                    <input type="text" class="form-control" id="usr" name="nama">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>
                <div class="form-group">
                    <label for="password">password:</label>
                    <input type="text" class="form-control" id="password" name="password">
                </div>
                <div class="form-group">
                    <label for="alamat">Coverage:</label>
                    <textarea class="form-control" id="alamat" name="alamat"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/barang') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/kontak_edit.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <h1>Anak IT -  Edit Kontak</h1>
            <hr>
            @foreach($data as $datas)
            <form action="{{ route('kontak.update', $datas->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="nama">Nama:</label>
                    <input type="text" class="form-control" id="usr" name="nama" value="{{ $datas->name }}">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ $datas->email }}">
                </div>
                <div class="form-group">
                    <label for="alamat">Coverage:</label>
                    <textarea class="form-control" id="alamat" name="alamat">{{ $datas->alamat }}</textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/kontak') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
            @endforeach
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/lokasi.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            <a class="btn btn-success" href="{{ route('lokasi.create') }}">Tambah Outlet</a>
            <hr>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>No.</th>
                    <th>Kode Outlet</th>
                    <th>Nama Outlet</th>
                    <th>Aksi</th>
                </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach($data as $datas)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $datas->kode_lokasi }}</td>
                        <td>{{ $datas->nama_lokasi }}</td>
                        <td>
                            <form action="{{ route('lokasi.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('lokasi.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/lokasi_create.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->

            <hr>
            <form action="{{ route('lokasi.store') }}" method="post">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="kode">Kode Outlet:</label>
                    <input required type="number" class="form-control" id="usr" name="kode" value="">
                </div>
                <div class="form-group">
                    <label for="nama">Nama Outlet:</label>
                    <input required type="text" class="form-control" id="nama" name="nama">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/lokasi') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/lokasi_edit.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            <hr>
            @foreach($data as $datas)
            <form action="{{ route('lokasi.update', $datas->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                <div class="form-group">
                    <label for="kode">Kode Outlet:</label>
                    <input type="number"class="form-control" id="kode" name="kode" value="{{ $datas->kode_lokasi}}">
                </div>
                <div class="form-group">
                    <label for="nama">Nama Outlet:</label>
                    <input type="text" class="form-control" id="nama" name="nama" value="{{ $datas->nama_lokasi }}">
                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Submit</button>
                    <a href="{{ url('/lokasi') }}" class="btn btn-md btn-danger">Cancel</a>
                </div>
            </form>
            @endforeach
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/pengiriman.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div>
            <center>
                <h2>Riwayat Pengiriman</h2>
            </center>
        </div>
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            {{-- <a class="btn btn-success" href="{{ route('register') }}">Daftar Sales</a>
            <hr> --}}

            <table class="table table-bordered">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>No Pengiriman</th>
                        <th>Tanggal</th>
                        <th>ID Lokasi</th>
                        <th>ID Barang</th>
                        <th>Jumlah Barang</th>
                        <th>Harga Barang</th>
                        <th>ID Kurir</th>
                        {{-- <th>Action</th> --}}
                    </tr>
                    </thead>
                    <tbody>
                    @php $no = 1; @endphp
                    @foreach($data as $datas)
                        <tr>
                            <td>{{ $no++ }}</td>
                            <td>ID{{ $datas->no_pengiriman }}</td>
                            <td>{{ $datas->tanggal }}</td>
                            <td>{{ $datas->lokasi_id }}</td>
                            <td>{{ $datas->barang_id }}</td>
                            <td>{{ $datas->jumlah_barang }}</td>
                            <td>{{ $datas->harga_barang }}</td>
                            <td>{{ $datas->kurir_id }}</td>
                            {{-- <td>
                                <form action="{{ route('barang.destroy', $datas->id) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <a href="{{ route('barang.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                </form>
                            </td> --}}
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </table>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection

resources/views/report.blade.php
@extends('base')
@section('content')
    <!-- Main Section -->
    <section class="main-section">
        <!-- Add Your Content Inside -->
        <div class="content">
            <!-- Remove This Before You Start -->
            @if(Session::has('alert-success'))
                <div class="alert alert-success">
                    <strong>{{ \Illuminate\Support\Facades\Session::get('alert-success') }}</strong>
                </div>
            @endif
            <hr>
            <a class="btn btn-success" href="{{ route('barang.create') }}">Tambah</a>
            <hr>

            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>No</th>
                    <th>No Pengiriman</th>
                    <th>Tanggal</th>
                    <th>ID Lokasi</th>
                    <th>ID Barang</th>
                    <th>Jumlah Barang</th>
                    <th>Harga Barang</th>
                    <th>ID Kurir</th>
                    {{-- <th>Action</th> --}}
                </tr>
                </thead>
                <tbody>
                @php $no = 1; @endphp
                @foreach($data as $datas)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>ID{{ $datas->no_pengiriman }}</td>
                        <td>{{ $datas->tanggal }}</td>
                        <td>{{ $datas->lokasi_id }}</td>
                        <td>{{ $datas->barang_id }}</td>
                        <td>{{ $datas->jumlah_barang }}</td>
                        <td>{{ $datas->harga_barang }}</td>
                        <td>{{ $datas->kurir_id }}</td>
                        {{-- <td>
                            <form action="{{ route('barang.destroy', $datas->id) }}" method="post">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('barang.edit',$datas->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                            </form>
                        </td> --}}
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.content -->
    </section>
    <!-- /.main-section -->
@endsection